name: Scala Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - scala-auth-api
          - scala-crud-api

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: us-east-1  # Replace with your desired AWS region

    - name: Build and push Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        cd ${{ matrix.project }}
        docker build -t $ECR_REGISTRY/${{ matrix.project }}:${{ github.sha }} .
        docker push $ECR_REGISTRY/${{ matrix.project }}:${{ github.sha }}
